### ISSUE TITLE
Numbers are not supported

### ISSUE THREAD

**Issue by abdoutech93** [linuxscout/festival-tts-arabic-voices#2]
Tested with arabic numerals like ١ , ٢, ٣ and default numerals like 1, 2, 3 with no success. the program ignore them.

**Comment by linuxscout** [comment]
ملاحظتك وجيهة،
سندقق هذه الأرقام بالتنويعة المشرقية،

لكن الأرقام العادية تعمل،
يمكن تحويلها قبل إرسالها للبرنامج هذا ما يجري حاليا،

لكن سنضيفها ايضا
